deda = input("dedatqvenis asaki: ")
mama = input("mamatqvenis asaki: ")
da = input("tqveni dis asaki: ")
print("dedatqveni iqneba ", int(deda) + 2 , " wlis ori wlis shemdeg")
print("mamatqveni iqneba ", int(mama) + 2 , " wlis ori wlis shemdeg")
print("tqveni da iqneba ", int(da) + 2 , " wlis ori wlis shemdeg")
